export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const CURRENT_CATEGORY = "CURRENT_CATEGORY";

export const SET_PORTFOLIO_PROJECTS = "SET_PORTFOLIO_PROJECTS";
export const REMOVE_PROJECT = "REMOVE_PROJECT";